In [ ]:
import numpy as np
# creating arrays
arr = np.array([1,2,3,4,5], dtype=int)
print(arr)

[1 2 3 4 5]


In [ ]:
zeros_arr = np.zeros((3, 3), dtype=int)
print(zeros_arr)
ones_arr = np.ones((2,2), dtype=int)
print(ones_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]


In [ ]:
arange_arr = np.arange(0,995,5)
print(arange_arr)


[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990]


NO.OF ROWS BECOME NO.OF GROUP
column become rows
group become column

In [ ]:
# Array manipulation
reshaped_arr = arr.reshaped(2,3,5)
print(reshaped_arr)
print(np.dstack)

AttributeError: 'numpy.ndarray' object has no attribute 'reshaped'

In [ ]:
sliced_arr = arr[2:4]
print(sliced_arr)

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b =a.T
print(b)
b=np.split(a,4)
print(b)

In [ ]:
      import numpy as np
      a = np.array([[1,2],[3,4]])
      b = np.array([[5,6],[7,8]])
      c=np.dot(a,b)
      print(c)
      d = np.linalg.eig(c)
      print(d)

In [ ]:
data = np.loadtxt("/content/drive/MyDrive/dataset/DAP.txt",dtype=int)
d = np.savetxt("/content/drive/MyDrive/dataset/DAP.txt",data)
print(d)
print(data)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
arange_ar=np.arange(0,1000,5)
print(arange_ar)
data=np.savetxt("/content/drive/MyDrive/dataset/DAP.txt",arange_ar)

In [ ]:
a=np.random.rand()
print(a)

In [ ]:
a=np.random.randint(1,1000)
print(a)

In [ ]:
a=np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.shape)


In [ ]:
a=np.linspace(8,20,5)
print(a)

In [ ]:
arange_ar=np.arange(24).reshape(3,2,4)
print(arange_ar)

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])
print(a*b)
print(a@b)
print(np.dot(a,b))

In [ ]:
from numpy import random

In [ ]:
a=np.ones([2,3],dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

In [ ]:
a=np.floor(np.random.random([2,12]))
print(a)

In [ ]:
a=np.ceil(np.random.random((2,12)))
print(a)

In [ ]:
a=np.array([[1,4],[5,8]])
print(a)
print(a.max())
print(a.min())
print(a.max(axis=1))
print(a.max(axis=0))

In [ ]:
a=np.array([[1,4],[5,8]])
print(a)
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))
print(a.cumsum())

In [ ]:
a=np.array([[1,4,5,8]])
print(a)
print(a.cumsum())

In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(3,2))
print(a)
print(a.shape)

None
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(2,3))
b=np.array([6,5,4,3,2,1])
print(b.resize(2,3))
print(np.vstack((a,b)))235
print(np.hstack((a,b)))

SyntaxError: invalid syntax (<ipython-input-36-3e9a646fd967>, line 5)

In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


-->No of rows becomes no of group -->Column becomes rows -->Group becomes coloumns

In [ ]:
import numpy as np
a1= np.eye(4)
print(a1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
a1 = np.full((2,2),3)
print(a1)
print(a1.itemsize)


[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)
print(a)


[1 2 3]


In [ ]:
x=np.array([1,4,0], float)
y=np.array([2,2,1], float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


create an one dimensional array

In [ ]:
x=np.array([1.1,4.3,0.8,2.6,3.3,5.5,7.2],float)
print(np.rint(x))

[1. 4. 1. 3. 3. 6. 7.]


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,1])
print(np.true_divide(a,b))

[0.16666667 0.28571429 0.375      0.44444444 5.        ]


In [ ]:
a=np.array([1,1,2,2,3,3,4,4])
print(np.unique(a))

[1 2 3 4]


In [ ]:
a=np.array([[1,7],[2,4]])
b=np.array([[1,6],[5,8]])
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))

[1 2 4 5 6 7 8]
[1]
[2 4 7]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)
print(np.sin(0))

10.0
0.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.mod(a,b))

[10  0  0  0  0 10]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.divide(a,b))

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.multiply(a,b))

[ 200  441   60  800 1250 1500]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.matmul(a,b))

4251


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[-0.54689092 -0.95034309  0.64344699]
 [-0.12655881  1.57481901  0.79306389]]


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[-0.76354685  6.302158    1.44089115]
 [-0.73945134 -0.86888036  0.44211128]]


In [ ]:
from numpy import random
x=random.binomial(n=12,p=0.5,size=10)#n=no of trails;p=probability
print(x)

[ 7  5  7  5  7  5  8  6 10  5]


In [ ]:
from numpy import random
x=random.poisson(lam=2,size=10)
print(x)

[1 2 2 1 1 0 1 2 2 1]


In [ ]:
from numpy import random
x=random.choice([1,2,3,4,5])
print(x)

1


In [ ]:
from numpy import random
a=(random.choice([3,5],p=[0.5,0.5],size=(3,4)))
print(a)

[[5 3 3 5]
 [3 3 5 5]
 [5 5 3 3]]
